from fastapi import FastAPI
from v1.endpoints import users, documents, folders, favorites
from core.settings import Settings

settings = Settings()

app = FastAPI(
    title=settings.app_name,
    description=settings.description,
    version="0.0.1"
)


app.include_router(users.router)
app.include_router(documents.router)
app.include_router(folders.router)
app.include_router(favorites.router)

app.openapi_tags = [
    users.tag_metadata,
    documents.tag_metadata,
    folders.tag_metadata,
    favorites.tag_metadata
]

# load_dotenv(settings.Config.env_file)

# DB Connection code example
# client = MongoClient(os.environ.get(settings.mongo_pass))
# BD2 = client.BD2
# notes = BD2.File
# users = BD2.User
# print(notes.find_one())
# print(users.find_one())
# client.close()



from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "Z2FQDZpR8flTzHPK4xhCP3s6"

# Found in the 'Manage Deployment' page
CLOUD_ID = "Elastic_Notilokos:c291dGhhbWVyaWNhLWVhc3QxLmdjcC5lbGFzdGljLWNsb3VkLmNvbTo0NDMkMzg5NTI3YWE0MGMyNGE4N2JjZDdhNzM5MzliZDlmYWYkNzc5MGVjNmYxMmVjNDhmNTk3MDI3YWZiZjcwZWNhNmM="
# CLOUD_ID = "deployment-name:dXMtZWFzdDQuZ2Nw..."
# 389527aa40c24a87bcd7a73939bd9faf
# https://elastic-notilokos.es.southamerica-east1.gcp.elastic-cloud.com

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())
print(client.search(index="", query={"match_all": {}}))
# {'name': 'instance-0000000000', 'cluster_name': ...}


